// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package delayQueue

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageReq struct {
	Messsage             string   `protobuf:"bytes,1,opt,name=messsage,proto3" json:"messsage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageReq) Reset()         { *m = MessageReq{} }
func (m *MessageReq) String() string { return proto.CompactTextString(m) }
func (*MessageReq) ProtoMessage()    {}
func (*MessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *MessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageReq.Unmarshal(m, b)
}
func (m *MessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageReq.Marshal(b, m, deterministic)
}
func (m *MessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageReq.Merge(m, src)
}
func (m *MessageReq) XXX_Size() int {
	return xxx_messageInfo_MessageReq.Size(m)
}
func (m *MessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_MessageReq proto.InternalMessageInfo

func (m *MessageReq) GetMesssage() string {
	if m != nil {
		return m.Messsage
	}
	return ""
}

type MessageData struct {
	TimeStamp            int64    `protobuf:"varint,1,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	Delay                int32    `protobuf:"varint,2,opt,name=delay,proto3" json:"delay,omitempty"`
	RetryCount           int32    `protobuf:"varint,3,opt,name=retryCount,proto3" json:"retryCount,omitempty"`
	Data                 string   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageData) Reset()         { *m = MessageData{} }
func (m *MessageData) String() string { return proto.CompactTextString(m) }
func (*MessageData) ProtoMessage()    {}
func (*MessageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *MessageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageData.Unmarshal(m, b)
}
func (m *MessageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageData.Marshal(b, m, deterministic)
}
func (m *MessageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageData.Merge(m, src)
}
func (m *MessageData) XXX_Size() int {
	return xxx_messageInfo_MessageData.Size(m)
}
func (m *MessageData) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageData.DiscardUnknown(m)
}

var xxx_messageInfo_MessageData proto.InternalMessageInfo

func (m *MessageData) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *MessageData) GetDelay() int32 {
	if m != nil {
		return m.Delay
	}
	return 0
}

func (m *MessageData) GetRetryCount() int32 {
	if m != nil {
		return m.RetryCount
	}
	return 0
}

func (m *MessageData) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type ReturnCommon struct {
	ReturnCode           int32    `protobuf:"varint,1,opt,name=returnCode,proto3" json:"returnCode,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReturnCommon) Reset()         { *m = ReturnCommon{} }
func (m *ReturnCommon) String() string { return proto.CompactTextString(m) }
func (*ReturnCommon) ProtoMessage()    {}
func (*ReturnCommon) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *ReturnCommon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnCommon.Unmarshal(m, b)
}
func (m *ReturnCommon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnCommon.Marshal(b, m, deterministic)
}
func (m *ReturnCommon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnCommon.Merge(m, src)
}
func (m *ReturnCommon) XXX_Size() int {
	return xxx_messageInfo_ReturnCommon.Size(m)
}
func (m *ReturnCommon) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnCommon.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnCommon proto.InternalMessageInfo

func (m *ReturnCommon) GetReturnCode() int32 {
	if m != nil {
		return m.ReturnCode
	}
	return 0
}

func (m *ReturnCommon) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type QueryListMessagesResp struct {
	ReturnCode           int32          `protobuf:"varint,1,opt,name=returnCode,proto3" json:"returnCode,omitempty"`
	Message              string         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MsgList              []*MessageData `protobuf:"bytes,3,rep,name=msgList,proto3" json:"msgList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *QueryListMessagesResp) Reset()         { *m = QueryListMessagesResp{} }
func (m *QueryListMessagesResp) String() string { return proto.CompactTextString(m) }
func (*QueryListMessagesResp) ProtoMessage()    {}
func (*QueryListMessagesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *QueryListMessagesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryListMessagesResp.Unmarshal(m, b)
}
func (m *QueryListMessagesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryListMessagesResp.Marshal(b, m, deterministic)
}
func (m *QueryListMessagesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListMessagesResp.Merge(m, src)
}
func (m *QueryListMessagesResp) XXX_Size() int {
	return xxx_messageInfo_QueryListMessagesResp.Size(m)
}
func (m *QueryListMessagesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListMessagesResp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListMessagesResp proto.InternalMessageInfo

func (m *QueryListMessagesResp) GetReturnCode() int32 {
	if m != nil {
		return m.ReturnCode
	}
	return 0
}

func (m *QueryListMessagesResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *QueryListMessagesResp) GetMsgList() []*MessageData {
	if m != nil {
		return m.MsgList
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageReq)(nil), "delayQueue.MessageReq")
	proto.RegisterType((*MessageData)(nil), "delayQueue.MessageData")
	proto.RegisterType((*ReturnCommon)(nil), "delayQueue.ReturnCommon")
	proto.RegisterType((*QueryListMessagesResp)(nil), "delayQueue.QueryListMessagesResp")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x89, 0x69, 0x8d, 0x99, 0x56, 0x0f, 0x8b, 0x7f, 0x96, 0x22, 0x12, 0x73, 0xca, 0x29,
	0x60, 0x7d, 0x01, 0xa5, 0xa2, 0x82, 0x7a, 0xe8, 0xfa, 0x04, 0xab, 0x19, 0x4a, 0x21, 0x9b, 0x4d,
	0xf7, 0xcf, 0x21, 0x77, 0x5f, 0xd5, 0xf7, 0x90, 0x6c, 0x36, 0x36, 0x42, 0xbd, 0xe8, 0x2d, 0xdf,
	0x37, 0x93, 0xdf, 0x7c, 0x33, 0x2c, 0x1c, 0x0a, 0xd4, 0x9a, 0xaf, 0x30, 0xaf, 0x95, 0x34, 0x92,
	0x40, 0x81, 0x25, 0x6f, 0x96, 0x16, 0x2d, 0xa6, 0x19, 0xc0, 0x4b, 0x57, 0x64, 0xb8, 0x21, 0x33,
	0x38, 0x68, 0x5b, 0x5b, 0x49, 0x83, 0x24, 0xc8, 0x62, 0xf6, 0xad, 0x53, 0x0b, 0x13, 0xdf, 0x79,
	0xc7, 0x0d, 0x27, 0xe7, 0x10, 0x9b, 0xb5, 0xc0, 0x57, 0xc3, 0x45, 0xed, 0x7a, 0x43, 0xb6, 0x35,
	0xc8, 0x31, 0x8c, 0xdd, 0x10, 0xba, 0x97, 0x04, 0xd9, 0x98, 0x75, 0x82, 0x5c, 0x00, 0x28, 0x34,
	0xaa, 0x59, 0x48, 0x5b, 0x19, 0x1a, 0xba, 0xd2, 0xc0, 0x21, 0x04, 0x46, 0x05, 0x37, 0x9c, 0x8e,
	0xdc, 0x68, 0xf7, 0x9d, 0x3e, 0xc2, 0x94, 0xa1, 0xb1, 0xaa, 0x5a, 0x48, 0x21, 0x64, 0xe5, 0x19,
	0x4e, 0x17, 0x5d, 0xc8, 0x8e, 0xe1, 0x1d, 0x42, 0x21, 0xf2, 0xdb, 0xba, 0xd9, 0x31, 0xeb, 0x65,
	0xfa, 0x11, 0xc0, 0xc9, 0xd2, 0xa2, 0x6a, 0x9e, 0xd7, 0xda, 0xf8, 0x55, 0x34, 0x43, 0x5d, 0xff,
	0x9d, 0x49, 0xae, 0x20, 0x12, 0x7a, 0xd5, 0x02, 0x69, 0x98, 0x84, 0xd9, 0x64, 0x7e, 0x96, 0x6f,
	0x8f, 0x9b, 0x0f, 0xee, 0xc5, 0xfa, 0xbe, 0xf9, 0x67, 0x00, 0x91, 0x2f, 0x90, 0x27, 0x38, 0x7a,
	0x40, 0x73, 0x5b, 0x96, 0x7d, 0x1c, 0x72, 0xba, 0xe3, 0x7f, 0x86, 0x9b, 0xd9, 0xe5, 0xd0, 0xdf,
	0xbd, 0xc5, 0x0d, 0x4c, 0xef, 0xa5, 0x7a, 0xc7, 0x1e, 0xfe, 0x1b, 0x8a, 0x0e, 0xfd, 0x1f, 0xb7,
	0xed, 0xe2, 0x0c, 0xc0, 0xff, 0x88, 0xf3, 0xb6, 0xef, 0x1e, 0xdb, 0xf5, 0x57, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x4d, 0xac, 0x5a, 0x79, 0x7d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MessageClient is the client API for Message service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessageClient interface {
	GetAllMessages(ctx context.Context, in *MessageReq, opts ...grpc.CallOption) (*QueryListMessagesResp, error)
	ForceMessage(ctx context.Context, in *MessageReq, opts ...grpc.CallOption) (*ReturnCommon, error)
	GetListMessage(ctx context.Context, in *MessageReq, opts ...grpc.CallOption) (*QueryListMessagesResp, error)
}

type messageClient struct {
	cc *grpc.ClientConn
}

func NewMessageClient(cc *grpc.ClientConn) MessageClient {
	return &messageClient{cc}
}

func (c *messageClient) GetAllMessages(ctx context.Context, in *MessageReq, opts ...grpc.CallOption) (*QueryListMessagesResp, error) {
	out := new(QueryListMessagesResp)
	err := c.cc.Invoke(ctx, "/delayQueue.Message/GetAllMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) ForceMessage(ctx context.Context, in *MessageReq, opts ...grpc.CallOption) (*ReturnCommon, error) {
	out := new(ReturnCommon)
	err := c.cc.Invoke(ctx, "/delayQueue.Message/ForceMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) GetListMessage(ctx context.Context, in *MessageReq, opts ...grpc.CallOption) (*QueryListMessagesResp, error) {
	out := new(QueryListMessagesResp)
	err := c.cc.Invoke(ctx, "/delayQueue.Message/GetListMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServer is the server API for Message service.
type MessageServer interface {
	GetAllMessages(context.Context, *MessageReq) (*QueryListMessagesResp, error)
	ForceMessage(context.Context, *MessageReq) (*ReturnCommon, error)
	GetListMessage(context.Context, *MessageReq) (*QueryListMessagesResp, error)
}

func RegisterMessageServer(s *grpc.Server, srv MessageServer) {
	s.RegisterService(&_Message_serviceDesc, srv)
}

func _Message_GetAllMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).GetAllMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/delayQueue.Message/GetAllMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).GetAllMessages(ctx, req.(*MessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_ForceMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).ForceMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/delayQueue.Message/ForceMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).ForceMessage(ctx, req.(*MessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_GetListMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).GetListMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/delayQueue.Message/GetListMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).GetListMessage(ctx, req.(*MessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Message_serviceDesc = grpc.ServiceDesc{
	ServiceName: "delayQueue.Message",
	HandlerType: (*MessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllMessages",
			Handler:    _Message_GetAllMessages_Handler,
		},
		{
			MethodName: "ForceMessage",
			Handler:    _Message_ForceMessage_Handler,
		},
		{
			MethodName: "GetListMessage",
			Handler:    _Message_GetListMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
